ALTER TABLE FUNCIONARIO 
ADD CONSTRAINT Cpf_supervisor 
FOREIGN KEY (Cpf_supervisor) 
REFERENCES FUNCIONARIO (Cpf);

ALTER TABLE FUNCIONARIO 
ADD CONSTRAINT Dnr 
FOREIGN KEY (Dnr) 
REFERENCES DEPARTAMENTO (Dnumero);

ALTER TABLE DEPARTAMENTO 
ADD CONSTRAINT Cpf_gerente 
FOREIGN KEY (Cpf_gerente) 
REFERENCES FUNCIONARIO (Cpf);

ALTER TABLE LOCALIZACAO_DEP 
ADD CONSTRAINT Dnumero 
FOREIGN KEY (Dnumero) 
REFERENCES DEPARTAMENTO (Dnumero);

ALTER TABLE PROJETO 
ADD CONSTRAINT Dnum 
FOREIGN KEY (Dnum) 
REFERENCES DEPARTAMENTO (Dnumero);

ALTER TABLE TRABALHA_EM 
ADD CONSTRAINT Fcpf 
FOREIGN KEY (Fcpf) 
REFERENCES FUNCIONARIO (Cpf);

ALTER TABLE TRABALHA_EM 
ADD CONSTRAINT Pnr 
FOREIGN KEY (Pnr) 
REFERENCES PROJETO (Projnumero);

ALTER TABLE DEPENDENTE 
ADD CONSTRAINT Fcpf2 
FOREIGN KEY (Fcpf) 
REFERENCES FUNCIONARIO (Cpf);